<?php
function kdv_custom_follow_networks_alter(&$networks, $uid = 0){
    $networks[$uid]['imdb'] =array(
        'title' => t('IMDB'),
        'domain' => 'imdb.com',
    );

    $networks[$uid]['drupal'] = array (
        'title' =>t('Drupal.org'),
        'domain' => 'drupal.org',
    );

    $networks[$uid]['twitter'] = array (
        'title' =>t('twitter'),
        'domain' => 'twitter.com',
    );

}
